server:
  port: 8087
spring:
  application:
    name: backoffice-bff
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/MSS
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: rqnWegoHwnvjBFepwYsTvSnsP5u8VP1D #gitleaks:allow
            scope: openid, profile, email, roles
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        # Changes for your local development should not be committed
        - id: api_product_local
          uri: http://localhost:8080
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_media_local
          uri: http://localhost:8083
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/media/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_tax_local
          uri: http://localhost:8091
          predicates:
            - Path=/api/tax/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api
          uri: http://api.mss.local
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
---
spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: api
          uri: http://nginx
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Origin Access-Control-Request-Method Access-Control-Request-Headers
            - TokenRelay=
            - StripPrefix=1
        - id: nextjs
          uri: http://backoffice-nextjs:3000
          predicates:
            - Path=/**
