server:
  port: 8080
  servlet:
    context-path: /product
    
spring:
  application:
    name: product
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/MSS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
        ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauthflow:
    authorization-url: http://identity/realms/MSS/protocol/openid-connect/auth
    token-url: http://identity/realms/MSS/protocol/openid-connect/token

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        type:
          descriptor:
              sql: trace

cors:
  allowed-origins: "*"

mss:
  services:
    media: http://localhost:8083/