server:
  port: 8093
  servlet:
    context-path: /payment-paypal

spring:
  application:
    name: payment-paypal
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/MSS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none

springdoc:
  packagesToScan: org.mss.payment.paypal
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauthflow:
    authorization-url: http://identity/realms/MSS/protocol/openid-connect/auth
    token-url: http://identity/realms/MSS/protocol/openid-connect/token

cors:
  allowed-origins: "*"