server:
  port: 8094
  servlet:
    context-path: /sampledata
    
spring:
  application:
    name: sampledata
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/MSS
  datasource:
    driver-class-name: org.postgresql.Driver
    product:
      url: jdbc:postgresql://localhost:5432/product
    media:
      url: jdbc:postgresql://localhost:5433/media
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

springdoc:
  packagesToScan: org.mss.sampledata
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauthflow:
    authorization-url: http://identity/realms/MSS/protocol/openid-connect/auth
    token-url: http://identity/realms/MSS/protocol/openid-connect/token

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    springframework:
      jdbc:
        core: DEBUG

cors:
  allowed-origins: "*"