server:
  port: 8091
  servlet:
    context-path: /tax

spring:
  application:
    name: tax
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://identity/realms/MSS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tax
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

springdoc:
  packagesToScan: org.mss.tax
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
  oauthflow:
    authorization-url: http://identity/realms/MSS/protocol/openid-connect/auth
    token-url: http://identity/realms/MSS/protocol/openid-connect/token

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

resilience4j:
  retry:
    instances:
      rest-api:
        max-attempts: 3
  circuitbreaker:
    instances:
      rest-circuit-breaker:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3

mss:
  services:
    location: http://localhost:8086/

cors:
  allowed-origins: "*"